PyData London 2024
ImperialCollegeLondon/RSEBlog pull request #15
Opened 2024-07-22 09:28 UTC by SaranjeetKaur

2024-07-22 13:09 UTC, SaranjeetKaur commented
@Sahil590 - looks like all the relevant content is on this PR now. I took the liberty to request for reviews. Please feel free to make any changes that you feel are appropriate.

2024-07-23 04:49 UTC, dalonsoa requested changes
Looks good to me! I've just suggested a couple minor changes.

2024-07-23 04:49 UTC, dalonsoa commented on docs/.authors.yml
> +    description: Research Software Engineer - HPC and RSE Experience Programme
We are about to change his job title.
```suggestion
    description: Research Software Engineer
```

2024-07-23 04:49 UTC, dalonsoa commented on docs/.authors.yml
Yes, use the group webpage photos, for consistency.

2024-07-23 04:49 UTC, dalonsoa commented on docs/posts/pydata_london_2024.md
> +  - Python
The post is already in the `Events` category, so I'm not sure if it is useful to add a `Conference` tag as well. Maybe replace with `PyData` directly. Also, maybe add `Open source` and `Machine learning` as it describes the content of several of the talks you mention.

2024-07-23 08:23 UTC, SaranjeetKaur commented on docs/posts/pydata_london_2024.md
> +  - Python
Done!

2024-07-23 09:00 UTC, SaranjeetKaur commented on docs/.authors.yml
done!

2024-07-23 09:05 UTC, dalonsoa approved these changes

2024-07-23 10:26 UTC, merged

2024-07-23 13:52 UTC, AdrianDAlessandro commented
This looks fantastic! And obviously is already merged, but one thing I'm curious about is if the images can be formatted to be centred and or made a specific size? They are currently all left-aligned and are different sizes.

It would be ideal if we could make it a global setting (maybe in a stylesheet) to align images in a specific way.

2024-07-23 14:46 UTC, SaranjeetKaur commented
> This looks fantastic! And obviously is already merged, but one thing I'm curious about is if the images can be formatted to be centred and or made a specific size? They are currently all left-aligned and are different sizes.
> 
> It would be ideal if we could make it a global setting (maybe in a stylesheet) to align images in a specific way.

Thanks @AdrianDAlessandro! We were wondering if we should re-size and align the images for consistency, because as of now we have used the images as they are (which it is not a good approach in the long run). I will create a separate issue based on your comment.