Blog post "Design Patterns in Financial Data Science"
ImperialCollegeLondon/RSEBlog pull request #22
Opened 2024-07-25 05:38 UTC by HarmonicReflux

This is a draft of my blog post about the use of Design Patterns in Financial Data Science. 

The focus is on the Strategy Pattern, with a detailed walk-through of its definition and implementation. I illustrate the practical use of this pattern with an example of pricing European put and call options, a common task in finance.

While I am aware that there are many other design patterns, this post specifically addresses the Strategy Pattern. I may need to revise the title to reflect this focus. I would appreciate feedback on the clarity and flow of information.

2024-07-25 23:43 UTC, HarmonicReflux commented
Weirdly, equations set in LaTeX do not render as expected on my local machine as seen in the below screenshot. Will they render correctly on github pages? 
![Screenshot from 2024-07-26 00-41-24](https://github.com/user-attachments/assets/6ff82982-628b-4e26-8f9c-fa5acb91036d)

2024-07-26 08:08 UTC, alexdewar commented
What are you using to render them @HarmonicReflux? The VS Code preview or are you building them with MkDocs?

2024-07-26 09:43 UTC, dc2917 commented on mkdocs.yml
> +  - plantuml_markdown
This needs adding to pyproject.toml.

However, `poetry add plantuml_markdown`, followed by `poetry run mkdocs build` gives me the following:

```
ERROR   -  Config value 'plugins': The "plantuml_markdown" plugin is not installed

Aborted with a configuration error!
```

2024-07-26 14:39 UTC, dc2917 requested changes
Personally I think the UML section should be removed or at least massively reduced, and that it would be better to just point to an external resource for understanding UML diagrams.

You say "Let us now implemented these pricing equations in a Python program..." and then immediately go into more UML.

If you really want to keep the UML then I'd change the title of the post reflect this, as well as the fact that you focus on the strategy design pattern, rather than a general overview of design patterns.

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> + [20 Mechanical Principles combined in a Useless Lego Machine" on YouTube [sic!]](https://www.youtube.com/watch?v=M1-YeqGynlw)
```suggestion
their philosophy is to find standard solutions to common problems in a given field.
```

I'm not sure this adds anything, but instead detracts the reader from your post very early on.

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +There are, also standard designs for car engines, for instance the four-stroke engine, or the shape of a kitchen sink in plumbing and house design.
```suggestion
There are also standard designs for car engines, for instance the four-stroke engine, or the shape of a kitchen sink in plumbing and house design.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +the "focus on the question at hand to answer a particular problem, while caring to a lesser degree, or not at all, on the design of the program".
This sentence lacks structure

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +Many Jupyter notebooks that are written in isolation, are a prime example of that. In that sense many data scientists are stuck on the "make it work"
```suggestion
Many Jupyter notebooks that are written in isolation are a prime example of that. In that sense many data scientists are stuck on the "make it work"
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +mantra, rather than progressing to "make it right", and, finally, "make it fast". That is not meant as a criticism, as more often than not, we rework, rewrite or re-manufacture entire parts of our co
```suggestion
mantra, rather than progressing to "make it right", and, finally, "make it fast". That is not meant as a criticism, as more often than not we rework, rewrite or re-manufacture entire parts of our code to achieve the "make it work" step, and over-engineering a piece of code can be seen as an issue in itself, at least at the prototyping, or "proof-of-concept" stage. For more mature systems, however, this leads to plenty of technical issues, which are difficult or even impossible to maintain.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +like other objects and even make functions take other functions as input parameters.
I think this is potentially misleading, so it would be good to get other opinions! Python is first and foremost an OOP language, where everything (including functions) is an object.

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +This blog is aimed at providing an overview of design patterns that one can make use for in `Financial Data Science` applications.
```suggestion
This article is aimed at providing an overview of design patterns that one can make use of in `Financial Data Science` applications.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +It does not claim to be exhaustive, and you are encouraged to take a look at the original publication, or even, to take the
```suggestion
It does not claim to be exhaustive, and you are encouraged to take a look at the original publication, or even to take the
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +UML is not a programming language but rather a tool used to help software developers visualise the design of a system.
Mix of visualise/visualize

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +Moreover, UML diagrams serve as a part of the documentation process, providing several types of diagrams that cater to different aspects of a software system. For example, use case diagrams for requi
```suggestion
Moreover, UML diagrams serve as a part of the documentation process, providing several types of diagrams that cater to different aspects of a software system. For example, use-case diagrams for requirements gathering, class diagrams for showing static structure, and sequence diagrams for detailing the interactions.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +UML hence is an important tool used across the software development lifecycle, from conceptualisation through to implementation. It helps teams communicate ideas more effectively and builds a foundat
```suggestion
Hence UML is an important tool used across the software development lifecycle, from conceptualisation through to implementation. It helps teams communicate ideas more effectively and builds a foundation for creating a robust architecture. By using UML, developers can ensure that their initial designs can be translated into functional software, making it an important part of modern software engineering practices.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +Form within Jupyter notebooks, we can make use of a library called `iplantuml` that we can install via pip upon invoking pip install iplantuml.
```suggestion
From within Jupyter notebooks, we can make use of a library called `iplantuml` that we can install via pip upon invoking `pip install iplantuml`.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +You can also use it to lay out the structure of your software using the package and use that as a basis for a research report or a dissertation. It is in general a good idea to keep a record of the b
```suggestion
You can also use it to lay out the structure of your software using the package and use that as a basis for a research report or a dissertation. It is in general a good idea to keep a record of the blueprint of your software, especially if you implement larger works or production systems.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +In the currency of the contract, under the Black-Scholes model, the price of a European call and put options given the underlying stock are hence :
```suggestion
In the currency of the contract, under the Black-Scholes model, the price of a European call and put options given the underlying stock are hence:
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +In this blog, we introduced design patterns and demonstrated how to implement the `Strategy Pattern` using the Object-Oriented paradigm in Python.
```suggestion
In this article, we introduced design patterns and demonstrated how to implement the `Strategy Pattern` using the Object-Oriented paradigm in Python.
```

2024-07-26 14:39 UTC, dc2917 commented on docs/posts/DesignPatterns.md
> +like other objects and even make functions take other functions as input parameters.
Especially given that your python code at the end is object-oriented.

2024-07-31 20:00 UTC, HarmonicReflux commented
> Personally I think the UML section should be removed or at least massively reduced, and that it would be better to just point to an external resource for understanding UML diagrams.
> 
> You say "Let us now implement these pricing equations in a Python program..." and then immediately go into more UML.
> 
> If you really want to keep the UML then I'd change the title of the post reflect this, as well as the fact that you focus on the strategy design pattern, rather than a general overview of design patterns.

ok, am re-working the text.

2024-08-20 22:19 UTC, HarmonicReflux commented
I am sorry to keep you guys waiting on this, but I somehow can not make mkdocs serve run although, I modified mkdocs.yml and pyproject.toml as per the request:
![Screenshot from 2024-08-20 23-16-54](https://github.com/user-attachments/assets/74c25696-bc45-4e65-8abf-bc270ba3768b)

2024-08-20 22:27 UTC, HarmonicReflux commented
I do not know why that is. 

May it be because of a conflict of the virtual environments?
I got pyenv on Linux installed to manage multiple python version, have a virtual environment for the RSEBlog itself (that I source activate and set in Pycharm as the interpreter for RSEBlog). But then there is also poetry.

As you see from the below screenshots, the multiple environments can get quite confusing and `pyenv shell` for setting a Python version in a terminal session can take no effect at all, whereas pyenv global overwrites everything. 

![Screenshot from 2024-08-20 23-10-01](https://github.com/user-attachments/assets/9fc1d6d8-203f-4642-975b-82fd91e7ef3e)
![Screenshot from 2024-08-20 23-10-15](https://github.com/user-attachments/assets/a5a5cc62-d848-477f-8080-58ad9b88e168)

2024-08-20 23:13 UTC, HarmonicReflux commented
Also, what I do find weird is that I activated my Python interpreter that was built by poetry, although, when I invoke `which python`, I am pointed to a version that contains the word "shim" in its folder structure. I.e. which python points to a version of python that was installed using pyenv, and that prevails . 

It really seems that pyenv battles with the environment set by poetry. May that be an issue indeed, or may I be simply overlooking something here?


![Screenshot from 2024-08-21 00-05-51](https://github.com/user-attachments/assets/1a0485f1-8937-4602-8249-5852b44cc70c)

2024-08-28 02:18 UTC, HarmonicReflux commented
The above issues have been taken care of in #52, which overwrites and closes this branch.

2024-08-28 02:26 UTC, closed without merging