CI: Check that blog builds without warnings
ImperialCollegeLondon/RSEBlog pull request #29
Opened 2024-07-29 17:58 UTC by alexdewar

Add a workflow to run MkDocs in strict mode to check for build warnings and errors.

Closes #25.

2024-07-30 08:25 UTC, SaranjeetKaur approved these changes
nice one!

2024-07-30 09:43 UTC, cc-a requested changes
Nice. A few suggestions.

2024-07-30 09:43 UTC, cc-a commented on .github/workflows/ci.yml
> +    branches: [main]
Won't this be inherently covered by the publish workflow?

2024-07-30 09:43 UTC, cc-a commented on .github/workflows/ci.yml
> +  release:
I don't think we're using releases.

2024-07-30 09:43 UTC, cc-a commented on .github/workflows/ci.yml
> +        run: poetry run mkdocs build -s
Super picky but I think it's nice to use the long form of flags in this sort of context for readability.

2024-07-31 08:47 UTC, alexdewar commented on .github/workflows/ci.yml
> +    branches: [main]
Kiiiind of. We're not building the docs in strict mode for the publish workflow though, which means warnings could creep in.

How about using strict mode for the publish workflow?

2024-07-31 08:51 UTC, cc-a commented on .github/workflows/ci.yml
> +    branches: [main]
That makes sense. At the moment having this workflow run on push wouldn't actually stop the publication from happening anyway so best to mae the strictness consistent.

2024-07-31 09:09 UTC, cc-a approved these changes
Great. Good stuff.

2024-07-31 09:13 UTC, merged