Adding the RSELondonSouthEast_2024 blog
ImperialCollegeLondon/RSEBlog pull request #37
Opened 2024-08-09 12:03 UTC by TinyMarsh

This PR adds the blog post for the RSELondonSouthEast24 workshop. This blog was jointly written by the team. The HackMD document can be found here: https://hackmd.io/F28JGV0sTYy8m4fzQuldxQ?both

Once Sahil's PR (#36) has been merged the following line will need to be added after the RSE logo to resize it to a sensible size;
```
{: style="height:300px;width:auto"}
```

2024-08-09 12:37 UTC, dc2917 approved these changes
Looks good, well done! I've made some minor wording and grammar suggestions.

2024-08-09 12:37 UTC, dc2917 commented on docs/posts/rslondonsoutheast_2024.md
> +Celebrating its fifth year, [the RSLondonSouthEast workshop returned] to Imperial College's South Kensington campus. [Imperial's RSE team] was well represented, with the event drawing RSEs and academ
```suggestion
Celebrating its fifth year, [the RSLondonSouthEast workshop returned] to Imperial College London's South Kensington campus. [Imperial's RSE team] was well represented, with the event drawing RSEs and academics from across London and the South East of England. This year's conference was organised by [Jeremy Cohen], from Imperial, and [Ilektra Christidi] from UCL. <!-- TODO: Check with Jeremy that this is true ;-) -->
```

2024-08-09 12:37 UTC, dc2917 commented on docs/posts/rslondonsoutheast_2024.md
> +As it has in previous years, the workshop continues to provide a welcoming and valuable platform for anyone involved in research software.
I feel the "as it has in previous years" is tautological - it's implied by saying the "workshop continues". Could just integrate this sentence in to the paragraph above?

2024-08-09 12:37 UTC, dc2917 commented on docs/posts/rslondonsoutheast_2024.md
> +[Diego Alonso Álvarez] is the RSE Team Lead at [Imperial College London]. A physicist by training with specialty in semiconductor nanostructures, he has led ICL's RSE team since 2021.
```suggestion
[Diego Alonso Álvarez] is the RSE Team Lead at [Imperial College London]. A physicist by training with specialty in semiconductor nanostructures, he has led Imperial's RSE team since 2021.
```

ICL isn't an official acronym (I also personally really don't like it 😅), but is Diego someone we met? Didn't we already know him?

2024-08-09 13:29 UTC, alexdewar commented
I think it might be useful to add @jcohen02 as a reviewer (hi, Jeremy!)... but he doesn't seem to appear as an option in the list of possible reviewers. Does he need to be invited to the repo in some way?

Jeremy: As you can probably see, we've put together a small blog post about RSLondonSouthEast 2024 and wondered if you'd have a mo to take a quick look? There are a few small details we wanted to double-check with you (e.g. whether we've missed off any organisers) and wanted to check if there were any other aspects of the conference you'd like to highlight.

2024-08-09 13:37 UTC, alexdewar commented on docs/posts/rslondonsoutheast_2024.md
> +Tony Chapman and Evelina Gabasova presented sponsor talks from [UKRI-EPSRC] and the [Society of Research Software Engineering], respectively.
I think I agree with all your other suggestions, but I think this comma should stay :stuck_out_tongue: 

(I'm clearly focussing on the important issues here :laughing: .)

2024-08-09 13:38 UTC, alexdewar commented on docs/posts/rslondonsoutheast_2024.md
> +[Diego Alonso Álvarez] is the RSE Team Lead at [Imperial College London]. A physicist by training with specialty in semiconductor nanostructures, he has led ICL's RSE team since 2021.
Good point. We do also plug our own team in a few places and mention @dalonsoa's talk + poster at the end, too.

2024-08-09 13:41 UTC, alexdewar commented
This is slightly off topic for this PR... but I'm wondering if we want to put a number/date at the start of the filenames for the blog posts. At the moment it's fairly manageable, but when we've got more of them it might be easier to navigate through the repo if they're in order.

2024-08-09 22:45 UTC, AdrianDAlessandro requested changes
A few metadata things that need to be fixed up

2024-08-09 22:45 UTC, AdrianDAlessandro commented on docs/posts/rslondonsoutheast_2024.md
> +date: 2021-11-22
This needs to change to the current date (or intended publication date?)

```suggestion
date: 2024-08-12
```

2024-08-09 22:45 UTC, AdrianDAlessandro commented on docs/posts/rslondonsoutheast_2024.md
> +  - Technology
This should be an Event category
```suggestion
  - Event
```

2024-08-09 22:45 UTC, AdrianDAlessandro commented on docs/posts/rslondonsoutheast_2024.md
> +  - Technology
I guess we should include relevant tags. Maybe these plus some about specific talk topics?
```suggestion
  - RSE
  - RSE Community
  - RSLondon
```

2024-08-09 22:45 UTC, AdrianDAlessandro commented on docs/posts/rslondonsoutheast_2024.md
> +<!-- more -->
I'd prefer to move this to just after the very first paragraph

2024-08-10 23:15 UTC, jcohen02 reviewed
Adding a few comments for now but I haven't had a chance to get through everything yet so further updates to follow.

2024-08-11 15:03 UTC, jcohen02 reviewed
I've added some more comments/suggestions and have now completed my review.

2024-08-11 15:03 UTC, jcohen02 commented on docs/posts/rslondonsoutheast_2024.md
> +Adrian D'Alessandro presented a poster on [The HPC and RSE Experience Programme], an initiative by the [Imperial College Research Computing Service] to provide an early career entry-point into RTP ca
```suggestion
Adrian D'Alessandro presented a poster on [The HPC and RSE Experience Programme], an initiative by the [Imperial College Research Computing Service] to provide an early career entry-point into RTP careers. The programme offers the opportunity to spend six-months working as an RSE within the Research Computing Service, and working alongside the HPC system administrators and user support staff. This presentation was taken as an opportunity to share the idea in the hope that other universities would also start similar programmes of their own.
```

2024-08-12 07:19 UTC, alexdewar commented
Thanks @jcohen02 for your helpful comments! :smile:

2024-08-12 09:16 UTC, SaranjeetKaur commented on docs/posts/rslondonsoutheast_2024.md
> +[RSLondonSouthEast] (formerly RSLondon) is a [regional RSE Community], seeking to bring together those involved in developing and using research software. This includes anyone who writes code as part
So do we have 3 names? Imperial RS Community, RSLondon community, and the RSLondonSouthEast community workshop? That feels a little confusing

2024-08-12 09:20 UTC, SaranjeetKaur approved these changes

2024-08-12 10:28 UTC, TinyMarsh commented on docs/posts/rslondonsoutheast_2024.md
> +Tony Chapman and Evelina Gabasova presented sponsor talks from [UKRI-EPSRC] and the [Society of Research Software Engineering], respectively.
Yeah sorry @dc2917, overruled on this one.

2024-08-12 11:03 UTC, TinyMarsh commented on docs/posts/rslondonsoutheast_2024.md
> +[Marion Weinzierl] from the [Institute of Computing for Climate Science] at the University of Cambridge presented the Keynote for the workshop: "Leading from within the research technical professiona
I've gone with your suggestion for now. Happy to amend later if the concensus calls for it.

2024-08-12 11:49 UTC, TinyMarsh commented
Thanks all. There were a number of changes so could probably do with another skin over by someone.

2024-08-12 16:03 UTC, AdrianDAlessandro approved these changes
Looks good to me!

2024-08-12 16:03 UTC, AdrianDAlessandro commented on docs/posts/rslondonsoutheast_2024.md
> +<!-- <!-- markdown-link-check-enable -->
Is this a typo? I wonder if it will prevent re-enabling link-checking after this point?

```suggestion
<!-- markdown-link-check-enable -->
```

2024-08-12 16:18 UTC, merged

2024-08-14 10:52 UTC, jcohen02 commented on docs/posts/rslondonsoutheast_2024.md
> +[RSLondonSouthEast] (formerly RSLondon) is a [regional RSE Community], seeking to bring together those involved in developing and using research software. This includes anyone who writes code as part
There are two separate communities with different committees, one is local (to Imperial) and one regional:

 - Imperial Research Software Community - our local research software community at Imperial started in 2015.
 - Research Software London (known as RSLondon for short) - a regional research software community for London and the South East of England. It has a committee consisting of people from a number of different institutions.
 
RSLondonSouthEast is the name of RSLondon's annual workshop - not unlike RSECon is the name of the annual conference run by the Society of Research Software Engineering.

2024-08-14 11:00 UTC, SaranjeetKaur commented on docs/posts/rslondonsoutheast_2024.md
> +[RSLondonSouthEast] (formerly RSLondon) is a [regional RSE Community], seeking to bring together those involved in developing and using research software. This includes anyone who writes code as part
Ok cool! Thanks for the clarification @jcohen02!