Additional features for blogs
ImperialCollegeLondon/RSEBlog pull request #41
Opened 2024-08-12 15:58 UTC by SaranjeetKaur

I have added a couple of lines about using admonitions. We might want to add some more features too.

2024-08-19 14:16 UTC, dc2917 requested changes

2024-08-19 14:16 UTC, dc2917 commented on README.md
> +Refer the [admonitions documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) to know more about the different types of admonitions and possible customisations.
```suggestion
Refer to the [admonitions documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) to know more about the different types of admonitions and possible customisations.
```

2024-08-19 14:16 UTC, dc2917 commented on README.md
> +Refer the [code blocks documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/) for more customisations.
```suggestion
Refer to the [code blocks documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/) for more customisations.
```

2024-08-19 14:16 UTC, dc2917 commented on README.md
> +- To add syntax highlighting to those blocks, add the language shortcode directly after the opening block.
Probably worth providing a link to a list of supported languages and their shortcode

2024-08-19 14:16 UTC, dc2917 commented on README.md
> +
Might be worth adding a short example to show how to format all of this, e.g. to show that the language name needs to be on the same line as the opening backticks etc

2024-08-19 14:21 UTC, AdrianDAlessandro commented on README.md
> +#### Customise images
For customising Images, I think links to the following is enough:
- [MkDocs Caption](https://tobiasah.github.io/mkdocs-caption/)
- [Attribute Lists](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists) in the Material Theme docs

2024-08-19 15:31 UTC, dc2917 reviewed
Just a couple of tiny changes but otherwise looks good to me!

2024-08-19 15:31 UTC, dc2917 commented on README.md
> +#### Customise images
```suggestion
#### Customising images
```

2024-08-19 15:31 UTC, dc2917 commented on README.md
> +- To add a custom title to the code block use `title="<custom title>"` option directly after the language shortcode. Here is an example of a Python code block that adds three numbers:
```suggestion
- To add a custom title to the code block use `title="<custom title>"` option directly after the language shortcode.

Here is an example of a Python code block that adds three numbers:

```

2024-08-20 11:18 UTC, dc2917 approved these changes

2024-08-20 11:29 UTC, SaranjeetKaur commented
Thanks folks! I will merge this PR now.

2024-08-20 11:29 UTC, merged