Update authors in posts
ImperialCollegeLondon/RSEBlog pull request #44
Opened 2024-08-14 15:19 UTC by dalonsoa

In two of the posts transfered form the old blog I appear as author, but I am not. It was like that in the original blog because there was no other choice, but now there is, so let's make sure the right people appears as author.

I'm not sure who attended RSECon22. I've added everyone I think was there, but to be honest I'm not sure who was actually there and participated, so amend as needed.

2024-08-14 20:18 UTC, dc2917 commented on docs/posts/rsecon_2022.md
> +  - dc2917
```suggestion
```

2024-08-14 20:20 UTC, dc2917 requested changes
Removed myself from RSECon22 post author list as I hadn't joined yet

2024-08-16 11:52 UTC, jamesturner246 approved these changes
LGTM :+1:

2024-08-16 12:59 UTC, dc2917 approved these changes

2024-08-19 11:43 UTC, AdrianDAlessandro commented on docs/posts/rsecon_2022.md
> +  - AdrianDAlessandro
I don't remember being involved in this blog post. Does anyone know who wrote it?

2024-08-19 12:35 UTC, dalonsoa commented on docs/posts/rsecon_2022.md
> +  - AdrianDAlessandro
Possibly Dan Davies, now that I think about it. I should add him as co-author.

2024-08-20 08:53 UTC, merged