My RSE blog post makes a contribution towards explaining UML and the …
ImperialCollegeLondon/RSEBlog pull request #52
Opened 2024-08-28 01:45 UTC by HarmonicReflux

My RSE blog post makes a contribution towards explaining UML and the Strategy Design Pattern followed by a practical example from option pricing.

In particular, we:
- Introduce UML and its role in software architecture
- Detail the Strategy Pattern and its components (Context, Strategy Interface, Concrete Strategy)
- Include a practical example of pricing European options using the Black-Scholes-Merton equation
- Integrate relevant mathematical expressions and explanations
- 
Closes #22.

2024-08-28 09:50 UTC, dalonsoa requested changes
I've given a first pass to the post. It looks very good, but it will require several revisions until it is polished enough for publication.

I've left a few comments below but the main points are:

1. You need to add some links between sections to facilitate the reader to move naturally form one to another. As it is now, you seem to jump from one topic to another with no clear reason.
2. I'm a bit unsure about including equations. They are not complicated and I think it is nice to make it clear what you are solving, but they can be very obscure to someone not in the financial world. Maybe, to facilitate people going through them, explain what they are about, what they are useful for, etc. `European Call` and `European Put` don't say much.
3. Your premise for using UML diagram is to get to a code that is not overengineer but your code is very overengineer. You are using classes where you only need simple functions, which is one of the main criticisms of OOB: not everything needs to be a class! I've suggested a change that will improve that part, but obviously the UML diagrams will need updating accordingly. Probably things can be simplified further, but let's leave it here and see what others have to say.

2024-08-28 09:50 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +  - Software Engineering principles
I would suggest simplifying the tags as the following, considering you don't touch functional programming:
```suggestion
  - Design Patterns
  - Object Oriented Programming
  - Python
  - Financial Data Science
  - Software Engineering principles
  - UML Diagrams
```

2024-08-28 09:50 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +In the following, we first describe UML diagrams and how they are used to plan and visualise software architecture before coding itself.
This paragraph here comes a bit out of the blue after the nice introduction above. I would suggest something along the lines of:

> In this blog post we will... (some indication of the overall purpose of the post, linking the above introduction to what is coming next). We first start describing UML diagrams...

2024-08-28 09:50 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +UML includes a set of graphic notation techniques to create visual representations of Object-Oriented software systems.
So, UML diagrams are not useful for functional programming?

2024-08-28 09:50 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +## The `Strategy` Design Pattern
You are talking about UML and then suddenly jump to describe specific design patterns. There has to be some link between both sections for the post to read well and be fluid. Why UML helps you with this design pattern? I'm sure you know it, but it is not clear in the text.

2024-08-28 09:50 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +        return price
I don't understand why these need to be classes. That IS overengineer the problem. The following will work equally well, and keep any static type checker happy:

```suggestion
OptionPriceStrategy: Callable[['BlackScholesOption'], float]

# implement the European call option pricing strategy
def european_call_strategy(self, option: 'BlackScholesOption') -> float:
    d1, d2 = option.compute_d1_d2()
    price = (option.stock_price * norm.cdf(d1) -
        option.strike_price * np.exp(-option.risk_free_rate * option.time_to_maturity) * norm.cdf(d2))
    return price

# implement the European put option pricing strategy
def european_put_strategy(self, option: 'BlackScholesOption') -> float:
    d1, d2 = option.compute_d1_d2()
    price = (option.strike_price * np.exp(-option.risk_free_rate * option.time_to_maturity) * norm.cdf(-d2) -
        option.stock_price * norm.cdf(-d1))
    return price
```

And then... see other comments.

2024-08-28 09:50 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +    print(f"Put price: {put_price:.2f} [monetary units].")
And this can be re-written as:
```suggestion
    # method to compute the option price using the provided strategy
    def compute_option_price(self, strategy: OptionPriceStrategy) -> float:
        return strategy(self)

# main function to demonstrate the usage of the Strategy Pattern
def main() -> None:
    # create a Black-Scholes option with given parameters
    option: BlackScholesOption = BlackScholesOption(
        stock_price=100,
        strike_price=100,
        time_to_maturity=1,
        risk_free_rate=0.05,
        volatility=0.2
    )

    # compute and print the call option price using the call strategy
    call_price: float = option.compute_option_price(european_call_strategy)
    print(f"Call price: {call_price:.2f} [monetary units].")

    # compute and print the put option price using the put strategy
    put_price: float = option.compute_option_price(european_put_strategy)
    print(f"Put price: {put_price:.2f} [monetary units].")
```

In summary: don't make classes out of things that do not need to be classes.

2024-08-30 12:54 UTC, jamesturner246 requested changes
Nice to see info on UML and API design :+1: 

I've added a few points and suggestions. One other thing I note is the title: I feel this content is just as applicable to software developers in other computational fields. Maybe emphasise in the title that the content is more about API design using UML, and (with less emphasis) using a computational finance problem as an example.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +# Applying the Strategy Pattern: UML diagrams and Python for European option pricing
This title seems a bit difficult to unpack, given the intended audience might not yet know about any of them. Maybe something less specific like e.g.  'Code structuring with UML diagrams for financial software'.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +In the following, we first describe UML diagrams and how they are used to plan and visualise software architecture before coding itself.
Agree. Describing how this blog post will address the issues identified in the good introduction above would make the contents and goal of the post more clear. Even if it's obvious to you, it's a reassurance for the reader that they are not just being clickbaited.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +While it is not a programming language, UML serves as a helpful tool for helping software developers plan and design software architecture.
... and also helps in the onboarding of new developers in the team.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +UML simplifies communication, making it easier for both development teams and external stakeholders to understand the software design.
... also incentivises forward planning of a structured API, rather than retroactively having to standardise a crap API in the future.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +## The `Strategy` Design Pattern
Agree.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +
Here would be a perfect point to link back to the issues described in the intro: how does using the strategy pattern (also planning and documenting it with the nice UML diagram) help alleviate the intro issues? It's obvious to us, of course, but presumably the person reading this is unfamiliar with softeng norms and doesn't see the problem with churning out crap code fast.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +As an example we pick pricing a European call and put option using the `Black-Scholes-Merton` equation, which is
I'd hazard a guess that 80% of the audience doesn't know what, or the significance of, any of these things. You may need to spoon feed people a bit here. Briefly why use/what is a European call, the Black-Scholes-Merton equation. Some people might not even know what a PDE is.

2024-08-30 12:54 UTC, jamesturner246 commented on docs/posts/design_patterns.md
> +The `_compute_option_price` method takes an `OptionPriceStrategy` instance and uses it to compute the option price.
I'd make it clear here the link to the language used in the Strategy pattern description. "The BlackScholesOption class implements the 'context' of the pattern described earler... " or words to that effect.

2024-09-02 01:20 UTC, HarmonicReflux commented
Hello team, 

thanks for the feedback. 

I certainly can expand on the background and elaborate more on the the mathematical framework. 

I am aware on can borrow the ideas from "Design Patterns" and code them in a functional approach rather than an OOP one. I am not sure whether there is a silver bullet here. The main issue of the OOP approach is, that all variables feeding into the equation can be functions of multiple parameters, particularly, the can be time-dependent. I thought an OOP approach might make it easier to inherit from base classes for such an expansion, but of course, this would necessitate multiple inheritance making things nested. 

I am on RSECon this week, so will not be able to contribute this week.

2024-09-16 14:46 UTC, dalonsoa commented
> I am aware on can borrow the ideas from "Design Patterns" and code them in a functional approach rather than an OOP one. I am not sure whether there is a silver bullet here. The main issue of the OOP approach is, that all variables feeding into the equation can be functions of multiple parameters, particularly, the can be time-dependent. I thought an OOP approach might make it easier to inherit from base classes for such an expansion, but of course, this would necessitate multiple inheritance making things nested.

I totally understand why you are using OOP, but in the example you use, it just results in the opposite idea you are trying to communicate, how to not over engineer your code. There might be other cases where that is the right approach, but I don't think that is the answer in this one. There's no benefit on using classes in this case. 

I'd suggest you either come up with an example where using classes is indeed the best approach (eg. if there's a state that needs to be pre-calculated or setup, and then used when needed) or modify your code the way I suggested and re-write the text to match the example.

On the background, I think that's a must. Otherwise, only people with some background in finance will understand what's going on.

Maybe have a crack at Jame's and my comments and then ask the rest of the reviewers to have a look to the revised version, so we can iteratively improve the blog post.

2024-10-21 00:58 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +        return price
I was inspired by the original Gang of Four book and aimed at translating their scaffold into Python. I am aware a functional approach is often more direct to implement and maybe I am guilty of "disguising something as an object that just as well can be a function". I chose the OOP approach on purpose and it was the initial goal to code up the Strategy Pattern in an OOP fashion.

2024-10-21 01:00 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +## The `Strategy` Design Pattern
The idea is to have a visual representation, or a representation at all for that matter, that tells the reader what is being implemented. Seeing the code as such and translating it to a "structure" is difficult. Seeing the "structure" beforehand, i.e. metaphorically speaking, the blue print, before the actual building is built should make it easier.

2024-10-21 01:00 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +UML includes a set of graphic notation techniques to create visual representations of Object-Oriented software systems.
No, UML's are universal in nature, as the name suggests.

2024-10-21 01:04 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +In the following, we first describe UML diagrams and how they are used to plan and visualise software architecture before coding itself.
It is the least of my intention to deliver click-bait. I have a few concepts to explain here: 
- The design patterns and its purpose
- How it can be applied to a concrete example (here: option pricing from finance which essentially is pricing an insurance contract given uncertainty of future evolution of an underlying asset (and hence it is called a "derivative"))
- Incidentally, this forces me to also explain the concept of said derivatives as otherwise it pops out of nowhere for readers unfamiliar with the topic. 

Hence, it is not that easy to cater for all interests in the introduction.

2024-10-21 01:05 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +  - Software Engineering principles
I made these changes in my local copy.

2024-10-21 01:16 UTC, HarmonicReflux commented
I did work on improving the description of the background as to not loose readers unfamiliar with the terms straight away. 

Regarding OOP vs. functional. I do not have to keep track of the state of the object, but rather to compute a parameter based on inputs (the inputs are mapped to an output via an algebraic manipulation). So indeed the functional approach is the more direct approach here.

2024-10-21 01:16 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +As an example we pick pricing a European call and put option using the `Black-Scholes-Merton` equation, which is
I did address this point in my latest commit.

2024-10-22 13:24 UTC, dalonsoa requested changes
The finance related background and the link between the introduction and the UML diagrams is now much better - and indeed pretty interesting!

However, all the UML diagrams still use the class-based approach which, I think we agreed, is not the right call. Maybe you're already on it, but just a reminder.

2024-10-22 13:24 UTC, dalonsoa commented on docs/posts/design_patterns.md
> +  - Software Engineering principles
And why are not in the remote?

2024-10-24 16:48 UTC, AdrianDAlessandro requested changes
I tried running this locally and got:

```
ERROR   -  Config value 'plugins': The "plantuml_markdown" plugin is not installed
```

You will need to add this package to the dependencies (with `poetry add`) and make sure it works

2024-10-25 04:05 UTC, HarmonicReflux commented
> The finance related background and the link between the introduction and the UML diagrams is now much better - and indeed pretty interesting!
> 
> However, all the UML diagrams still use the class-based approach which, I think we agreed, is not the right call. Maybe you're already on it, but just a reminder.

Indeed, I am working on the UML diagrams.

2024-10-25 04:09 UTC, HarmonicReflux commented
> I tried running this locally and got:
> 
> ```
> ERROR   -  Config value 'plugins': The "plantuml_markdown" plugin is not installed
> ```
> 
> You will need to add this package to the dependencies (with `poetry add`) and make sure it works

This is a tricky bit: I had a discussion a while back ago with @alexdewar 
and we could not find a way to integrate `plantuml` with poetry. 

I create the diagrams in a jupyter notebook like so:
![Screenshot from 2024-10-25 05-07-01](https://github.com/user-attachments/assets/10db2247-5a55-4b28-b72d-72de2a5d3153)

This, unfortunately, is not supported using out RSEBlog repository.

2024-10-25 07:21 UTC, dalonsoa commented
I suggest you switch to using Mermaid, which has full support for [class diagrams](https://mermaid.js.org/syntax/classDiagram.html) (maybe not full featured UML ones, although I'm not sure of the difference) and do work with MkDocs. As it is not an extra dependency, but some sort of markdown extension, there should be no issues with poetry. It is even rendered in GitHub directly.

We have use it in QwikApp:

- Here [the config in mkdocs.yml](https://github.com/ImperialCollegeLondon/QwikApp_web/blob/fd34642ae240b4617dd66e4907a18988236bcc55/mkdocs.yml#L20-L24)
- Here [an example of usage](https://github.com/ImperialCollegeLondon/QwikApp_web/blob/main/docs/services.md) within the same docs

2024-10-25 07:52 UTC, HarmonicReflux commented
Morning @dalonsoa,
I struggle making my .md file pass markdownlint.
for example the first error indicated in the screenshot below is related to an invalid link. 

[Design Patterns: Elements of Reusable Object-Oriented Software](https://www.amazon.com/Design-Patterns-Elements-Reusable-Object-Oriented/dp/0201633612)

throws the indicated error, while a test link, say,
[SocRSE Youtube channel](https://www.youtube.com/channel/UCL7rYOIAP1Rx_VajLPDF-hA)

works just fine. Not sure what the issue is caused by. I tried to run 
` pre-commit run all-files` but the falg `all-files`  appears not to be defined  as per the error message `No hook with id `all-files` in stage `pre-commit``. Do you have an idea why my link is flagged invalid?

![Screenshot from 2024-10-25 08-44-52](https://github.com/user-attachments/assets/65e13ee6-ca3b-46e0-a5b2-84b0d6ba3c83)

2024-10-25 07:55 UTC, HarmonicReflux commented
> I suggest you switch to using Mermaid, which has full support for [class diagrams](https://mermaid.js.org/syntax/classDiagram.html) (maybe not full featured UML ones, although I'm not sure of the difference) and do work with MkDocs. As it is not an extra dependency, but some sort of markdown extension, there should be no issues with poetry. It is even rendered in GitHub directly.
> 
> We have use it in QwikApp:
> 
> * Here [the config in mkdocs.yml](https://github.com/ImperialCollegeLondon/QwikApp_web/blob/fd34642ae240b4617dd66e4907a18988236bcc55/mkdocs.yml#L20-L24)
> * Here [an example of usage](https://github.com/ImperialCollegeLondon/QwikApp_web/blob/main/docs/services.md) within the same docs

I have heard of Mermaid. Let me please first make my .md file pass the pre-commit hooks, so people can provide feedback on the text itself before taking a look at yet another tool.

2024-10-25 07:59 UTC, dalonsoa commented
Some webpages just don't let CI systems to check them easily. The simplest solution is jut to skip checking that link. Check this:
https://github.com/ImperialCollegeLondon/RSEBlog/blob/43789a708eb62825fa6dff7483641c570788b348/docs/posts/20240722_pydata_london_2024.md?plain=1#L31-L33

2024-10-25 08:02 UTC, dalonsoa commented
About the other error, you have the label and the link split in different lines. They render the same, but they are not the same thing and markdownlint will pick it:

<img width="428" alt="image" src="https://github.com/user-attachments/assets/a58beed6-63ca-47a2-a875-c5c3faf7dc98">

Do not split lines 17 and 18, even if it results in a long line.

2024-10-25 09:08 UTC, AdrianDAlessandro commented
> I tried running this locally and got:
> 
> ```
> ERROR   -  Config value 'plugins': The "plantuml_markdown" plugin is not installed
> ```
> 
> You will need to add this package to the dependencies (with `poetry add`) and make sure it works

@HarmonicReflux Sorry, I just realised I was on the old `DesignPatterns` branch and not this `DesignPatterns2` branch. I am no longer getting this error. I will delete the old branch from GitHub so the tab-completion doesn't prioritise that one.

2024-10-25 09:28 UTC, alexdewar commented
@HarmonicReflux If you update this branch now, you should end up with fewer CI errors to deal with.

2024-10-25 10:23 UTC, alexdewar commented on docs/posts/design_patterns.md
> +This blog post illustrates how the concept of a `Design Pattern` from the early 90ies can be translated to modern day Python. Given the 23 patterns introduced
```suggestion
This blog post illustrates how the concept of a `Design Pattern` from the early '90s can be translated to modern day Python. Given the 23 patterns introduced
```

2024-10-25 11:51 UTC, alexdewar commented on docs/posts/design_patterns.md
> +This blog post illustrates how the concept of a `Design Pattern` from the early 90ies can be translated to modern day Python. Given the 23 patterns introduced
This is the source of one of the spelling errors ("ies"):

```suggestion
This blog post illustrates how the concept of a `Design Pattern` from the early '90s can be translated to modern day Python. Given the 23 patterns introduced
```

2024-10-25 11:52 UTC, alexdewar commented on .wordlist.txt
> +ies
See my other comment

2024-10-25 11:52 UTC, alexdewar commented on .wordlist.txt
> +labeled
This is "labelled" in UK English. So I'd fix the text rather than ignoring the word.

2024-10-25 11:54 UTC, alexdewar commented on .wordlist.txt
> +Modeling
This is in here twice

2024-10-25 11:55 UTC, alexdewar commented on .wordlist.txt
> +se
Can we set the spellchecker to ignore two-letter words or something? Does anyone know? Having all these tiny non-words in the dictionary seems really ugly :grimacing:

2024-10-25 11:56 UTC, alexdewar commented on docs/posts/design_patterns.md
> +<!-- spell-check-ignore -->
If this works, then we can remove "Modeling" from `.wordlist.txt`, right?

2024-10-25 12:01 UTC, alexdewar commented on docs/posts/design_patterns.md
> +*The rendered result should look similar to the above figure.*
For figure captions, you can do this:

```md
![My figure caption.](path/to/image.png)
```

2024-10-25 12:01 UTC, alexdewar commented on docs/posts/design_patterns.md
> +We can identify the following relations in the UML diagram
```suggestion
We can identify the following relations in the UML diagram:
```

2024-10-25 12:02 UTC, alexdewar commented on docs/posts/design_patterns.md
> +*The rendered result should look similar to the above figure.*
See my comment above re figure captions.

2024-10-25 12:02 UTC, alexdewar commented on docs/posts/design_patterns.md
> +```zsh
This isn't a shell script :stuck_out_tongue:. Maybe this will work:

```suggestion
```txt
```

2024-10-25 12:05 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +<!-- spell-check-ignore -->
Yes, that should work. As with C++, I now have code that "compiles", and I now can work on make it more beautiful. But honestly, spellchecker has been a pain and to make it "behave" has been tricky. 

As for  the Latin phrase "per se", there is not much I can do about it. I do not use them that regularly, although they come across in economic language quite regularly, e.g. "ex-post [comparison]", "cum-ex [date]" , "ceteris paribus", and frankly e.g. and etc. are Latin words as well.   

I will remove "Modeling" from the wordlist. I cite the book as a reference. As it is by an American author, the title is with a single l rather a double l.

2024-10-25 12:06 UTC, HarmonicReflux commented on .wordlist.txt
> +labeled
mea culpa.

2024-10-25 12:09 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +```zsh
Lovely. That's what I was looking for in the first place.

2024-10-25 12:52 UTC, alexdewar commented on docs/posts/design_patterns.md
> +<!-- spell-check-ignore -->
I know it's correct -- we don't want to be changing the spelling of a title. I just meant that the `<!-- spell-check-ignore -->` bit should mean that it isn't flagged.

2024-10-25 12:54 UTC, alexdewar commented on docs/posts/design_patterns.md
> +<!-- spell-check-ignore -->
Re the Latin words (hah -- re is another), I wasn't asking you to change your text! I was just wondering if we could fix the spellchecker for some of the things that don't look like words (e.g. "nd" which I guess is part of "2nd" or something).

2024-10-26 06:09 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +<!-- spell-check-ignore -->
I also changed `Unified Modeling Language` to `Unified Modelling Language` to comply 
with the orthography of British English.

2024-10-26 06:17 UTC, HarmonicReflux commented on .wordlist.txt
> +se
I am are of this. `.wordlist.txt` has not been a beauty before my post and it will be ever lesser so after. 
I am happy for suggestions of other team members to modify spellchecker to resolve this.

I cannot trigger spellchecker locally to verify it runs error-free, and it got somewhat of a pain to make local changes to the `.spellcheck.yml` file and pushing them to the repo to trigger the CI pipeline only to experience it fails after 8 to 12 seconds and repeating the loop. 

In princliple one should be able to run spellchecker locally like so
```zsh
pip install pyspelling
pyspelling -c .spellcheck.yml
```
Also, in an experiment, I appended the following
```
  ignore_patterns:
    - '```[a-zA-Z]+\n[\s\S]*?\n```'  # Ignore code blocks
    - '## References\n(?:- .*\n)*'   # Ignore References section
```
to
.spellcheck.yml`
in order to test whether fenced code-blocks are protected from spellchecker doing its work on them, but to no avail. If someone wants to take a look at that, I think, it should be a separate issue. 

Also, I managed to protect the `References` section from spellchecker using
<!-- spell-check-ignore -->
References go here
<!-- end-spell-check-ignore -->
which works well.

2024-10-26 06:34 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +*The rendered result should look similar to the above figure.*
I follow your suggestion for the syntax, but am not able to break the caption like this

```mk
![This is the first line of the caption.<br>This should be the second line of the caption](path/to/image.png)
```

The result markdown renders doesn't look that great. Am thankful for suggestions.

2024-10-26 07:33 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +UML simplifies communication, making it easier for both development teams and external stakeholders to understand the software design.
Great. I added that to the post.

2024-10-26 07:34 UTC, HarmonicReflux commented on docs/posts/design_patterns.md
> +
I addressed the issue you point out here.

2024-10-26 08:39 UTC, HarmonicReflux commented
Disappointingly, my clickable references are not accepted by markdown. 
I thought it was a useful feature for the references directly linking to the bibliography. It works on my local copy and `markdown serve` renders everything beautifully:


[[Gemma et al. (1994)]](#gamma1994)
[[Booch et al. (2005)]](#booch2005) 
[[Shreve (2004)]](#shreve2004)

```
## References

<!-- spell-check-ignore -->
- <a id="gamma1994"></a> Gamma, E., Helm, R., Johnson, R., & Vlissides, J. *Design patterns: Elements of reusable object-oriented software.* Addison-Wesley, 1994.
- <a id="shreve2004"></a> Shreve, S. *Stochastic Calculus for Finance II: Continuous-Time Models.* Springer Finance, 2004.
- <a id="booch2005"></a> Booch, G., Rumbaugh, J., and Jacobson, I. *The Unified Modeling Language User Guide.* 2nd ed. Addison-Wesley, 2005.
<!-- end-spell-check-ignore -->
```

When pushing to the repo, I am thrown the following error:
``
markdownlint-fix.........................................................Failed
- hook id: markdownlint-fix
- exit code: 1
``

2024-10-26 08:55 UTC, HarmonicReflux commented
Forgive me @alexdewar for hacking `wordlist.txt` but having worked on this blog post  intensely, I really do not know why spellcheck is such a pain to work with. I leave modifications to it to a future issue. 

Also, I am not quite happy the `References` section is not interactive anymore, but I need to make 
`markdownlint-fix` happy so I can finally publish my work. Again, agreeing on a good-looking references section that keeps the links between the citation in the blog and the `References` section at the end,  is, in my oppinion, an issue for the future.

2024-10-27 17:19 UTC, HarmonicReflux commented
Voluntary extra task:

While I am thinking about the current implementation, we have now successfully and I think elegantly implemented the pricing equations for the put and call options using functional programming. 

One can actually take this a step further and compute sensitivities of the option price with respect to its dependent parameters. 

While maybe not to be included for this blog post, I wonder how to best build on the current software to implement the so-called "greeks" (they are nothing but sensitives, but one can, in fact, decompose the price of an option into these constituents).

For European options and binary options (that I do not consider in my blog), the greeks can be analytically computed, as can be seen from the sheet I compiled some time ago. 

Maybe when the review is done, we can have a chat how to extend the programme. I see we implement each greek using a respective function, but it get a bit convoluted then.

[Greeks.pdf](https://github.com/user-attachments/files/17534774/Greeks.pdf)

2024-10-28 15:52 UTC, dalonsoa approved these changes
I really like it. I've made one or two comments, but - aside from the spelling bit already being address - I think this is ready to go.

2024-10-28 15:52 UTC, dalonsoa commented on docs/posts/20241031_design_patterns_2024.md
> +```plantuml
This is meant to appear within a code block in Jupyter? Maybe mention that in the previous line.

2024-10-28 16:33 UTC, alexdewar approved these changes
LGTM! I've made some minor suggestions about formatting etc.

Two other things:

1. The inline references aren't currently clickable. I'd either put your references in footnotes (using [this markdown syntax](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/)) or into regular hyperlinks. (Even if you do the former, I'd still include a hyperlink to the article in the reference.)
2. There are some places where you're using backticks where italics or quote marks would be more appropriate. In markdown, backticks give you monospaced text (e.g. for code) not quotes (cf. LaTeX). That said, changing this is likely to be a pain and it's not a big deal, so I'm just making you aware really!

2024-10-28 16:33 UTC, alexdewar commented on docs/posts/20241031_design_patterns_2024.md
> +- iv) The actual implementation of pricing European options making use of the strategy pattern.
I'd make this a regular numbered list so it formats better:

```suggestion
1. As the patterns themselves are abstract in nature, we introduce the reader to their architecture via UML diagrams. UML stands for `Unified Modelling Language` and visualises the way and links through which systems interact with each other. This makes it particularly useful to visualise software. You might say - we have barely started and yet are off to a detour? Not really - at least not without ulterior motive. Having fundamental knowledge about UML diagrams will make it easier to facilitate the transition from the anatomy of the Design Pattern to the actual code, as the UML diagram serves as the blueprint we use to translate the pattern to code.
2. The definition of the Design Pattern we wish to make use of.
3. Some background of the application we apply the Design Pattern to. The author chose a common topic in finance, namely option pricing, specifically, European put and call options. Do not worry yet. We will introduce and explain the necessary vocabulary as well as the equations we implement as we go along.
4. The actual implementation of pricing European options making use of the strategy pattern.
```

2024-10-28 16:33 UTC, alexdewar commented on docs/posts/20241031_design_patterns_2024.md
> +- iv) The actual implementation of pricing European options making use of the strategy pattern.
(If you do this, you'll also need to change the references to the numbers in the text.)

2024-10-28 16:33 UTC, alexdewar commented on docs/posts/20241031_design_patterns_2024.md
> +## Yet more financial theory: Are the European options priced fair?
```suggestion
## Yet more financial theory: Are the European options priced fairly?
```

2024-10-28 16:33 UTC, alexdewar commented on docs/posts/20241031_design_patterns_2024.md
> +It is thus straight-forward to maintain and extend one part of the `concrete strategy` without affecting the other. This is a useful property if multiple team members simultaneously work on the same
```suggestion
It is thus straightforward to maintain and extend one part of the `concrete strategy` without affecting the other. This is a useful property if multiple team members simultaneously work on the same code base.
```

2024-10-28 16:33 UTC, alexdewar commented on docs/posts/20241031_design_patterns_2024.md
> +```
This doesn't need to be indented:

```suggestion
```python
call_price = option.compute_option_price(european_call_strategy)  # compute and print the call option price using the call strategy
put_price = option.compute_option_price(european_put_strategy)  # compute and print the put option price using the put strategy

# verify if the put-call parity holds:
present_value_strike = option.strike_price * np.exp(-option.risk_free_rate * option.time_to_maturity)  # present value of strike price

# implement the left and right side of the put-call parity equation
left_side = call_price + present_value_strike
right_side = put_price + option.stock_price

print(f"call price: {call_price:.2f} [monetary units].")
print(f"put price: {put_price:.2f} [monetary units].")
print(f"present value of strike price: {present_value_strike:.2f} [monetary units].")
print(f"left side (C + PV(K)): {left_side:.2f} [monetary units].")
print(f"right side (P + S): {right_side:.2f} [monetary units].")
print(f"put-call parity holds: {np.isclose(left_side, right_side)}")
```
```

2024-10-28 16:33 UTC, alexdewar commented on .wordlist.txt
> +labeled
```suggestion
```

2024-10-29 09:26 UTC, HarmonicReflux commented
> LGTM! I've made some minor suggestions about formatting etc.
> 
> Two other things:
> 
> 1. The inline references aren't currently clickable. I'd either put your references in footnotes (using [this markdown syntax](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/)) or into regular hyperlinks. (Even if you do the former, I'd still include a hyperlink to the article in the reference.)
> 2. There are some places where you're using backticks where italics or quote marks would be more appropriate. In markdown, backticks give you monospaced text (e.g. for code) not quotes (cf. LaTeX). That said, changing this is likely to be a pain and it's not a big deal, so I'm just making you aware really!

Hello @alexdewar,
I had the references being clickable, but then the markdown lint pre-commit hooks complained. I would have very much preferred clickable references though. Please see me elaborating on this point earlier in the discussion [here](https://github.com/ImperialCollegeLondon/RSEBlog/pull/52#issuecomment-2439434092)

2024-10-29 09:40 UTC, alexdewar commented
> Disappointingly, my clickable references are not accepted by markdown. I thought it was a useful feature for the references directly linking to the bibliography. It works on my local copy and `markdown serve` renders everything beautifully:
> 
> [[Gemma et al. (1994)]](#gamma1994) [[Booch et al. (2005)]](#booch2005) [[Shreve (2004)]](#shreve2004)
> 
> ```
> ## References
> 
> <!-- spell-check-ignore -->
> - <a id="gamma1994"></a> Gamma, E., Helm, R., Johnson, R., & Vlissides, J. *Design patterns: Elements of reusable object-oriented software.* Addison-Wesley, 1994.
> - <a id="shreve2004"></a> Shreve, S. *Stochastic Calculus for Finance II: Continuous-Time Models.* Springer Finance, 2004.
> - <a id="booch2005"></a> Booch, G., Rumbaugh, J., and Jacobson, I. *The Unified Modeling Language User Guide.* 2nd ed. Addison-Wesley, 2005.
> <!-- end-spell-check-ignore -->
> ```
> 
> When pushing to the repo, I am thrown the following error: `` markdownlint-fix.........................................................Failed
> 
> * hook id: markdownlint-fix
> * exit code: 1
>   ``

What's the full error message you get?

2024-10-29 09:59 UTC, AdrianDAlessandro approved these changes
I haven't read through the content in detail, but I'm happy to trust Diego and the many iteration that this has gone through. I've got one comment so it publishes cleanly. 

Also, I agree with Alex about providing links to the references, whichever way is convenient.

2024-10-29 09:59 UTC, AdrianDAlessandro commented on docs/posts/20241031_design_patterns_2024.md
> +
We need to put this break in here so the home page crops the article
```suggestion

<!-- more -->

```

2024-10-29 12:29 UTC, dc2917 requested changes
Typo/grammar/wording fixes

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +by Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides which are collectively known as the "Gang of Four" [[Gamma et al. (1994)]](#gamma1994).
```suggestion
by Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides, who are collectively known as the "Gang of Four" [[Gamma et al. (1994)]](#gamma1994).
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +in the referenced books split up into four *Creational Patterns*, seven *Structural Patterns*, and 11 *Behavioural Patterns*, we limit our efforts to one specific pattern,
```suggestion
in the referenced book are split up into four *Creational Patterns*, seven *Structural Patterns*, and 11 *Behavioural Patterns*, we limit our efforts to one specific pattern,
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +and software architects plan and design their software.
fix me

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +As part of ingredient one, we briefly outline the nuts and bolts of UML here, but for the interested reader, it is referred
```suggestion
As part of ingredient one, we briefly outline the nuts and bolts of UML here, but for the interested reader, refer
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +and is meant to simplify communication, making it easier for both, development teams and external stakeholders
```suggestion
and is meant to simplify communication, making it easier for both development teams and external stakeholders
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +- Interface (Strategy): Represented by a rectangular box labeled with interface at the top. This symbol signifies that Strategy defines a conceptual contract (or "interface") in terms of method signa
```suggestion
- Interface (Strategy): Represented by a rectangular box labelled with interface at the top. This symbol signifies that Strategy defines a conceptual contract (or "interface") in terms of method signature rather than implementation.
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +Note, while [[Gamma et al. (1994)]](#gamma1994) use an Object-Oriented approach to implement the strategies, but we find it more straightforward and easier-to-read-code to take a functional approach
```suggestion
Note, while [[Gamma et al. (1994)]](#gamma1994) use an Object-Oriented approach to implement the strategies, we find it more straightforward and easier-to-read-code to take a functional approach here.
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +Until the 1970ies, there did not exist a published rigorous mathematical framework to determine the fair price of
```suggestion
Until the 1970s, there did not exist a published rigorous mathematical framework to determine the fair price of
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +In honour of the Mathematician and Economist who were first attributed to find such a mathematical framework,
```suggestion
In honour of the mathematician and economist who were first attributed to find such a mathematical framework,
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +As you can see, the concrete strategies that the *Strategy Pattern* demands us to implement are the pricing equations for both, the European put and European call option.
```suggestion
As you can see, the concrete strategies that the *Strategy Pattern* demands us to implement are the pricing equations for both the European put and European call option.
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +should look like, we can start coding it up. Planning software like this may be very different from just coding spontaneously with less preparation, however we now know exactly what parts the softwar
```suggestion
should look, we can start coding it up. Planning software like this may be very different from just coding spontaneously with less preparation, however we now know exactly what parts the software
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +further analysis or concrete actions in the options market. Moreover, and perhaps more relevant in immediate practice is that merge conflicts are avoided and code reviews are easier to facilitate.
```suggestion
further analysis or concrete actions in the options market. Moreover, and perhaps more relevant in immediate practice, is that merge conflicts are avoided and code reviews are easier to facilitate.
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +However, if you are willing to real still a little more, we can turn to the question of how one can assess whether the computed option prices are fair.
```suggestion
However, if you are willing to read still a little more, we can turn to the question of how one can assess whether the computed option prices are fair.
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +As both, the left and right side of the equation of the put-call parity are equal, we can confidently say that the option prices computed by our software are accurate, reflecting the efficiency of th
```suggestion
As both the left and right sides of the equation of the put-call parity are equal, we can confidently say that the option prices computed by our software are accurate, reflecting the efficiency of the
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +engineering, ensuring that the code is understandable, extendable, and maintainable. Also, in an addendum, we made use of the computed output prices and utilised the *put-call parity* to confirm the
```suggestion
engineering, ensuring that the code is understandable, extensible, and maintainable. Also, in an addendum, we made use of the computed output prices and utilised the *put-call parity* to confirm the
```

2024-10-29 12:29 UTC, dc2917 commented on docs/posts/20241031_design_patterns_2024.md
> +options are priced fair.
```suggestion
options are priced fairly.
```

2024-10-29 12:57 UTC, dalonsoa commented on docs/posts/20241031_design_patterns_2024.md
> +and software architects plan and design their software.
```suggestion
While it is not a programming language per se, it helps software developers
and architects plan and design their software.
```

2024-10-29 12:58 UTC, dalonsoa commented on docs/posts/20241031_design_patterns_2024.md
> +We can code up the UML diagram of the Strategy pattern in a Jupyter notebook using *plantuml* as follows.
```suggestion
We can code up the UML diagram of the Strategy pattern in a code block of a Jupyter notebook using *plantuml* as follows.
```

2024-10-29 13:14 UTC, jamesturner246 approved these changes
Looking good! :+1:

2024-10-29 13:24 UTC, HarmonicReflux commented on docs/posts/20241031_design_patterns_2024.md
> +and software architects plan and design their software.
Thanks Dan... That is done now.

2024-10-29 13:36 UTC, dalonsoa commented
@dc2917 , we only need your approval.

2024-10-29 13:43 UTC, dc2917 approved these changes

2024-10-29 13:58 UTC, merged

2024-10-29 14:15 UTC, SaranjeetKaur commented on docs/posts/20241031_design_patterns_2024.md
> +author:
@HarmonicReflux - this might be `authors` instead?

2024-10-29 14:22 UTC, dalonsoa commented on docs/posts/20241031_design_patterns_2024.md
> +author:
Yep. Fixed in #68

2024-10-29 14:26 UTC, SaranjeetKaur commented on docs/posts/20241031_design_patterns_2024.md
> +author:
Perfect!