Add a template for writing blogs
ImperialCollegeLondon/RSEBlog pull request #56
Opened 2024-09-12 10:41 UTC by SaranjeetKaur

2024-09-12 10:48 UTC, SaranjeetKaur commented
The checks say that the HackMD link is dead. Should I publish the HackMD before using it here or any other ideas?

2024-09-12 13:38 UTC, dalonsoa requested changes
I would suggest to remove the references to "speed blog" from the template, and the suggested word limit. None of those are really applicable to our case.

Also, the template is not meant to be used "as is" in the blog, but rather to _guide writing_ the blog. Maybe it should be explained that after the blog is done, the document should be stripped from everything but the actual blog contents.

2024-09-12 13:38 UTC, dalonsoa commented on README.md
> +- Create a `.md` file for your blog in the `docs/posts` folder and add the blog content to it. You can use a [HackMD template for writing (collaborative) blogs](https://hackmd.io/@SaranjeetKaur/H17O8
Disable the checks for that line

```suggestion
<!-- markdown-link-check-disable-next-line -->
- Create a `.md` file for your blog in the `docs/posts` folder and add the blog content to it. You can use a [HackMD template for writing (collaborative) blogs](https://hackmd.io/@SaranjeetKaur/H17O8IzcC/edit). To edit the template, please sign in with, say, GitHub. This template is inspired from [Collaborations Workshop 2024](https://www.software.ac.uk/workshop/collaborations-workshop-2024-cw24)'s speed blog template.
```

It will also disabled checking the SSI link, but I don't think we can do much if the are in the same paragrpah.

2024-09-16 08:06 UTC, dalonsoa approved these changes
Now LGTM!!

2024-09-16 11:01 UTC, merged