RSECon24 blogpost
ImperialCollegeLondon/RSEBlog pull request #57
Opened 2024-09-20 12:15 UTC by SaranjeetKaur

Some to-dos:
- [ ] Add appropriate link to Emily's and Jeremy's avatar image in the `docs/.authors.yml` file
- [ ] Jeremy might want to add some links to the STEP-UP project

2024-09-20 12:22 UTC, SaranjeetKaur commented
Adrian and Ryan are away, but they are also contributors to this blogpost

2024-09-23 15:03 UTC, dc2917 approved these changes
I've made a couple of minor wording suggestions but otherwise looks good to me!

2024-09-23 15:03 UTC, dc2917 commented on docs/posts/20240920_rsecon_2024.md
> +There was an [Emerging Voices plenary](https://rsecon24.society-rse.org/programme/emerging-voice-plenary/) session on day 2 of the conference in which Deborah Udoh from Nigeria and Jack Atkinson from
```suggestion
There was an [Emerging Voices plenary](https://rsecon24.society-rse.org/programme/emerging-voice-plenary/) session on day 2 of the conference in which Deborah Udoh from Nigeria and Jack Atkinson from Cambridge presented their viewpoints on the work of RSEs. Both were clearly focussed on setting up and providing communities in their spheres of influence.
```

> "Deborah Udoh from Nigeria and Jack Atkinson from Cambridge"

Should we be more specific about their institutions/affiliations here? Nigeria is a country and Cambridge is a city.

2024-09-23 15:03 UTC, dc2917 commented on docs/posts/20240920_rsecon_2024.md
> +[RSE Worldwide](https://rsecon24.society-rse.org/programme/rse-worldwide/) is a regular track at RSECon. During these sessions representatives from national and regional RSE associations (and communi
```suggestion
[RSE Worldwide](https://rsecon24.society-rse.org/programme/rse-worldwide/) is a regular track at RSECon. During these sessions representatives from national and regional RSE associations (and communities) across the globe are encouraged to present updates from their regions. This year there were two sessions for RSE Worldwide to accommodate people from different timezones. There were discussions on the challenges faced, how to foster collaborations, and how to better support each other.
```

2024-09-23 15:03 UTC, dc2917 commented on docs/posts/20240920_rsecon_2024.md
> +The [Intersectional EDIA and Allies BoF](https://virtual.oxfordabstracts.com/#/event/49081/submission/139) brought together a community of those from marginalised backgrounds along with allies who we
```suggestion
The [Intersectional EDIA and Allies BoF](https://virtual.oxfordabstracts.com/#/event/49081/submission/139) brought together a community of those from marginalised backgrounds along with allies who were keen to support their struggles. This linked well with the earlier session, co-led by Jeremy Cohen on [Practical diversity and inclusion for Research Technical Professionals](https://virtual.oxfordabstracts.com/#/event/49081/submission/143), and both sessions provided resources for the community to aid in ensuring inclusive and accessible events in the future.
```

2024-09-23 15:07 UTC, SaranjeetKaur commented
@dalonsoa - could you please help with linking Jeremy's and Emily's avatar photos? I am not sure how to link them from the Imperial profiles

2024-09-23 15:16 UTC, dalonsoa commented
- Jeremy: https://profiles.imperial.ac.uk/jeremy.cohen/photo   <- Not sure if this will actually work
- Emily: https://www.imperial.ac.uk/media/images/portrait-2000x3000/Emily-Lumley2.jpg

Not sure how long the last one will work as it is for Emily's old group. Let's use it, for now.

2024-09-23 15:25 UTC, EmChem79 commented on docs/posts/20240920_rsecon_2024.md
> +There was an [Emerging Voices plenary](https://rsecon24.society-rse.org/programme/emerging-voice-plenary/) session on day 2 of the conference in which Deborah Udoh from Nigeria and Jack Atkinson from
I think that's a good point. Should we change it to "Rivers State, Nigeria" but keep Cambridge as is?

2024-09-24 13:45 UTC, SaranjeetKaur commented on docs/posts/20240920_rsecon_2024.md
> +There was an [Emerging Voices plenary](https://rsecon24.society-rse.org/programme/emerging-voice-plenary/) session on day 2 of the conference in which Deborah Udoh from Nigeria and Jack Atkinson from
Done!

2024-09-24 14:43 UTC, dalonsoa requested changes
It looks really good, but I think it needs something else at the end.

2024-09-24 14:43 UTC, dalonsoa commented on docs/posts/20240920_rsecon_2024.md
> +Overall RSECon24 was a great learning and networking experience!
Maybe add a bit more content here? It feels a little bit abrupt. How do you felt at the conference? Was it relaxing or intense and exhausting? How was Newcastle, the venue and the organisation of the event itself? Did you learnt anything specific useful you will take home? Where's the next one?

It doesn't need to be long, but a paragraph wrapping up the event and the blog post seems necessary.

2024-09-24 19:55 UTC, SaranjeetKaur commented on docs/posts/20240920_rsecon_2024.md
> +Overall RSECon24 was a great learning and networking experience!
I added a couple of sentences there - not a lot though

2024-09-25 08:29 UTC, dalonsoa approved these changes
All good! Ready to merge, from my side.

2024-09-25 09:21 UTC, alexdewar requested changes
It looks great as it is, but I've made some minor suggestions about wording and things. Feel free to ignore some/all of them.

I'll have a go at fixing the markdown link checker problem and I'll push the result directly to this branch.

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +It's now a little over 12 years since the term "Research Software Engineering" (RSE) was first coined at an [event held in Oxford, UK](https://www.software.ac.uk/blog/not-so-brief-history-research-so
```suggestion
It's now a little over 12 years since the term "Research Software Engineering" (RSE) was first coined at an [event held in Oxford, UK](https://www.software.ac.uk/blog/not-so-brief-history-research-software-engineers-0). Seeing around 400 people gather at the Frederick Douglass Centre at Newcastle University for this year's RSE Conference &ndash; [RSECon24](https://rsecon24.society-rse.org/) &ndash; was proof of the amazing growth that we've seen within the community and the wide range of opportunities that now exist to undertake software development work within the research domain. We know that career opportunities within the research technical professionals space are also expanding rapidly but there's still a way to go in recognising and rewarding the people who contribute vital technical skills to support and undertake research. This year's conference offered a wide range of talks, workshops and Birds of a Feather (BoF) sessions, alongside a great opportunity to network with other RSEs and researchers and catch up with friends both old and new. This growth of the community, opportunities for the future and how we can help to support and grow careers, as well as making our community more diverse and inclusive, were some of the topics covered at this year's conference. Several members of the Imperial College London Research Computing Service were in attendance at the conference, as were other RSEs and researchers from departments across the institution. In this blog post, we talk about our experiences, highlights and key takeaways from this year's conference.
```

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +It's now a little over 12 years since the term "Research Software Engineering" (RSE) was first coined at an [event held in Oxford, UK](https://www.software.ac.uk/blog/not-so-brief-history-research-so
Minor nit, but long dashes look nicer than hyphens

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +### Databases/query languages
```suggestion
### Query languages and databases
```

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +<!-- markdown-link-check-disable-next-line -->
Hmm... I'd prefer it if we could fix the failure by changing the MLC config file rather than just disabling it. I'll take a look at this.

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +### Working better with Python/Software
```suggestion
### Working better with Python
```

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +Developing a Python package that conforms to all of the best recommendations can be challenging. There are many ways to structure it and the recommendations seem to constantly change. This only gets
```suggestion
Developing a Python package that conforms to all of the best recommendations can be challenging. There are many ways to structure it and the recommendations seem to constantly change. This only gets more difficult when you consider what to include for the best quality _research_ software. In a workshop, we were shown how to easily build a Python package (or update an existing one) using [The Netherlands eScience Centre Python Template]( https://research-software-directory.org/software/nlesc-python-template).
```

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +Writing tests is a very important part of writing high quality software. Having a suite of comprehensive tests provides confidence that the software is working as intended, and can catch unintentiona
```suggestion
Writing tests is a very important part of writing high quality software. Having a suite of comprehensive tests provides confidence that the software is working as intended and can catch unintentional changes in behaviour while you're making changes. In one session, Abhishek Dasgupta demonstrated some advanced Python testing concepts like [mocking](https://docs.python.org/3/library/unittest.mock-examples.html), [property-based testing](https://hypothesis.works/articles/getting-started-with-hypothesis/) and [snapshot testing](https://github.com/syrupy-project/syrupy). In another, Thomas Hawes ran a workshop on how [Test Driven Development](https://github.com/UniExeterRSE/rsecon24-tdd-workshop/tree/main) can not only improve your test coverage, but also the quality of the code and your development efficiency.
```

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +Writing tests is a very important part of writing high quality software. Having a suite of comprehensive tests provides confidence that the software is working as intended, and can catch unintentiona
Just a suggestion about wording

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +Although software has become a predominant part of the scientific process, the true impact of RSEs is sometimes hard to evidence. This lack of evidence is in part because purely scientific publicatio
```suggestion
Although software has become a predominant part of the scientific process, the true impact of RSEs is sometimes hard to evidence. This lack of evidence is in part because purely scientific publications tend to leave little place for the software part of the research process while favouring the scientific results themselves. In 2016, the [Journal of Open Source Software (JOSS)](https://joss.theoj.org) was created to tackle this issue. JOSS is a peer-reviewed academic journal created with the objective of publishing papers about research software itself, giving the RSE world a route for recognition. A walkthrough provided an overview of the types of [submissions published in JOSS](https://joss.readthedocs.io/en/latest/submitting.html) and demonstrated the full life-cycle of the JOSS process, from the submission of the software and paper, to the review process and the final publication &ndash; explaining both sides of the coin: the submitter and reviewer's point of views.
```

Another dash :wink:

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +### Various reproducibility-related talks
```suggestion
### Towards more reproducible research
```

Maybe something like the above might be better? ^^

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +Within Imperial and in collaboration with University College London, King's College London and University of Westminster, the STEP-UP project (link) is working to help Research Technical Professional
```suggestion
Within Imperial and in collaboration with University College London, King's College London and University of Westminster, the [STEP-UP project](https://www.kcl.ac.uk/news/new-programme-supporting-research-technical-professionals-announced) is working to help Research Technical Professionals (RTPs) with many of these issues; advocating for EDIA within the profession and working towards a more comprehensive career pathway for RTPs within the academic environment.
```

This is the best link I could find ^^, but it's just an announcement on a news page. @jcohen02 do you have a better one?

2024-09-25 09:21 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +Overall RSECon24 was a great learning and networking experience. It was an intense week of discussions and interactions with the broader RSE community on a range of topics from good practices in soft
```suggestion
Overall RSECon24 was a great learning and networking experience. It was an intense week of discussions and interactions with the broader RSE community on a range of topics from good practices in software development to publishing software papers. We look forward to RSECon25 which will be hosted by the University of Warwick in Coventry.
```

2024-09-25 09:40 UTC, alexdewar commented on docs/posts/20240920_rsecon_2024.md
> +<!-- markdown-link-check-disable-next-line -->
I ended up just disabling requests to sqlitebrowser.org in the config file anyway, which is arguably no better! I was hoping we could get it to actually check the link by fiddling with some options.

I've pushed it anyway, but feel free to revert

2024-09-25 13:56 UTC, alexdewar approved these changes

2024-09-25 13:56 UTC, merged