Spellcheck action
ImperialCollegeLondon/RSEBlog pull request #62
Opened 2024-10-14 16:21 UTC by TinyMarsh

Removes the `codespell` hook and introduces the Spellcheck GitHub Action.

It currently runs on all `.md` files. A custom wordlist was created based on the spelling errors detected on the first pass (there were quite a few). Most of the words added are names and RSE-specific words/acronyms.

Closes #26

2024-10-15 08:47 UTC, dc2917 commented on .wordlist.txt
> +programme
Must be American English if it doesn't recognise "programme"

2024-10-15 08:57 UTC, dc2917 requested changes
Looks like this uses EN-US. Would the action actually change "colour" -> "color" or just mark it as a typo? We could potentially just add EN-GB spellings to the word list as we go along.

Either way, I've left some comments on the word list. Presumably some of them could be fixed with hyphenations, e.g. backend -> back-end, but I'm never sure when to hyphenate such things 😅

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +ai
Is this a word?

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +eg
This should be e.g. anyway
```suggestion
```

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +envirtonment
```suggestion
```

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +github
```suggestion
GitHub
```

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +html
Does it recognise HTML?

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +Javascript
Does it recognise JavaScript?

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +larning
Is this a word?

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +linux
Does it recognise Linux?

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +th
Is this a word? Is this for something like "8th"?

2024-10-15 08:57 UTC, dc2917 commented on .wordlist.txt
> +Youtube
Does it recognise YouTube?

2024-10-15 09:24 UTC, alexdewar requested changes
I've made some small suggestions. I'm not convinced by this though tbh. It seems like you have to add looooads of exceptions to the custom wordlist to make it work and from the list it seems like the spellchecker is also running over code blocks and things, because there are GitHub usernames and things like `eval` and `html` in there.

Happy to be swayed though!

2024-10-15 09:24 UTC, alexdewar commented on .github/workflows/ci.yml
> -          cache: poetry
This removes the caching, but it would be nice to keep it.

I think you can just drop the `actions-poetry` bit and replace it with:

```yaml
- name: Install poetry
  run: pipx install poetry
```

You still need to do this before `setup-python` though.

2024-10-15 09:24 UTC, alexdewar commented on .spellcheck.yml
> +    lang: en
Will this work?

```suggestion
    lang: en_GB
```

The action's readme page says it supports British English.

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +AdrianDAlessandro
Does this appear in a markdown file anywhere? Or just a config file?

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +alexdewar
Ditto

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +de
?

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +programme
Looks like you can set it to UK English -- see my comment above

2024-10-15 09:24 UTC, alexdewar commented on docs/posts/20240722_pydata_london_2024.md
> +Another interesting talk was Antonio Feregrino's lockdown project aiming to [recommend cards for a competitive Yu-Gi-Oh deck](https://www.youtube.com/watch?v=kYtj7spnppE). This used online data of hi
Another unicode quote mark:

```suggestion
Another interesting talk was Antonio Feregrino's lockdown project aiming to [recommend cards for a competitive Yu-Gi-Oh deck](https://www.youtube.com/watch?v=kYtj7spnppE). This used online data of high-level, competitive players' decks to recommend similar cards to ones you already have. It also involved a healthy dose of nostalgia for the early 2000s.
```

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +Commandline
I don't think this is one word:

```suggestion
```

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +github
Is "GitHub" in the default dictionary?

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +Hackathon
Do you need both of these forms in the dictionary? Would just the lowercase one do it?

2024-10-15 09:24 UTC, alexdewar commented on .wordlist.txt
> +macOS
Is just one of these correct?

2024-10-15 14:01 UTC, TinyMarsh commented on .wordlist.txt
> +ai
Turns out this is part of a name of a software called "H20.ai". Spellchecker picked up "ai" as being wrong so that's why it's in there. I've changed it to "H20.ai" in the wordlist now. Let's see what happens.

2024-10-15 14:14 UTC, TinyMarsh commented on .wordlist.txt
> +AdrianDAlessandro
"Abdelrazek" and "Abhishek" appear in the text. "AdrianDAlessandro" appears in the front matter in some of the markdowns. I don't know how to configure spellchecker to not look at the front matter.

2024-10-15 14:15 UTC, TinyMarsh commented on .wordlist.txt
> +alexdewar
Again, front matter.

2024-10-15 14:16 UTC, TinyMarsh commented on .wordlist.txt
> +de
No idea. Will remove from wordlist and see what happens.

2024-10-15 14:21 UTC, TinyMarsh commented on .wordlist.txt
> +macOS
Oh I think it's actually styled "macOS" - no capitalisation. Why are Apple like this.

2024-10-15 16:07 UTC, TinyMarsh commented on .wordlist.txt
> +de
Turns out this is part of a name (Andrie de Vries). I tried adding the full "Andrie de Vries" to the wordlist but it still didn't like the "de", so "de" has to be in the wordlist. Not ideal.

2024-10-15 16:18 UTC, TinyMarsh commented
Thanks for your feedback @dc2917 and @alexdewar.

There's a few things I have noticed along the way that are probably worth pointing out;
- Parts of names that contain words like "de" will get flagged as a spelling error. Adding the full name to the wordlist does not fix this. It means that the wordlist has to contain "de" which is not nice.
- Similarly, nouns that contain hyphenated words like "Yu-Gi-Oh" will cause the spellchecker to flag "Yu" and "Gi" separately, meaning those words have to also be added to the wordlist.
- There does not seem a way to configure the spellchecker to not check the front matter of the markdown file, meaning that any authors (specifically their GitHub usernames) will need to be added to the wordlist.
- I have added additional configuration for code fences. Meaning that words like "eval" can be removed from the wordlist.

2024-10-15 16:24 UTC, dc2917 commented
> Parts of names that contain words like "de" will get flagged as a spelling error. Adding the full name to the wordlist does not fix this. It means that the wordlist has to contain "de" which is not nice.
Similarly, nouns that contain hyphenated words like "Yu-Gi-Oh" will cause the spellchecker to flag "Yu" and "Gi" separately, meaning those words have to also be added to the wordlist.

Maybe these two things actually work together - means we can use "de" as a prefix and have things like "de-emphasize" haha.

> I have added additional configuration for code fences. Meaning that words like "eval" can be removed from the wordlist.

Nice, yeah I did wonder about that.

2024-10-15 16:28 UTC, dc2917 commented on README.md
> +You can then add to the attribute list to further specify the style. A useful one is for centring images:
Interesting (intresting? 😅), never thought about the spelling of that haha

2024-10-15 16:28 UTC, dc2917 approved these changes

2024-10-15 16:42 UTC, dalonsoa approved these changes
I can understand having to put in the list all names, acronyms, and the like. But there are things that are just ridiculous. If that's the best this tool can do, so be it, but even the spellchecker in Word is smarter than this one...

2024-10-15 16:42 UTC, dalonsoa commented on .wordlist.txt
> +walkthroughs
Why is this highlighted? It seems proper English to me.

2024-10-15 16:42 UTC, dalonsoa commented on .wordlist.txt
> +reproducibility
And these two?

2024-10-15 16:42 UTC, dalonsoa commented on .wordlist.txt
> +math
seriously?

2024-10-15 16:42 UTC, dalonsoa commented on .wordlist.txt
> +funder
What?

2024-10-15 19:07 UTC, TinyMarsh commented on .wordlist.txt
> +walkthroughs
Apparently "walkthrough" is not in the dictionary this tool uses. Although it is in the British English dictionary: https://dictionary.cambridge.org/dictionary/english/walkthrough

2024-10-15 19:13 UTC, TinyMarsh commented on .wordlist.txt
> +reproducibility
Not in the Cambridge English dictionary at least: https://dictionary.cambridge.org/dictionary/english/reproducibility

2024-10-15 19:14 UTC, TinyMarsh commented on .wordlist.txt
> +math
Yeah this is a weird one. Not sure why this one wouldn't be in the dictionary, but it isn't and so needs to be added.

2024-10-15 19:19 UTC, TinyMarsh commented on .wordlist.txt
> +funder
https://www.oed.com/dictionary/funder_n?tab=factsheet#113740568: "This word is used in U.S. English.".

This might be one of those Americanisms that isn't technically in the British English dictionary. I think it's worth adding though.

2024-10-16 08:15 UTC, alexdewar commented on .wordlist.txt
> +math
I guess it's an Americanism.

2024-10-16 08:21 UTC, alexdewar commented
Thanks @TinyMarsh. I think the code fences thing is a big improvement... obvs we have a lot of code blocks! I'm happy to merge this.

There is also this one: https://github.com/streetsidesoftware/cspell-action

No idea if it's any better, but it uses the same spellchecker as this VS Code extension, which I find doesn't have too many false negatives: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2024-10-16 08:21 UTC, alexdewar approved these changes

2024-10-16 08:28 UTC, merged